
services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - appnet
  db:
    container_name: database
    image: postgres:13
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=182705
      - POSTGRES_DB=learn2nihon
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    # THÊM KHỐI LỆNH healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d learn2nihon"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/certs:/etc/nginx/certs/:ro
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge