
services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    # Faster than copy but can cause some problem about security, shouldn't do this
    # volumes: # Giữ lại volume để code được đồng bộ
      # - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - appnet
  db:
    container_name: database
    image: postgres:13
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"  # Thêm port mapping cho database  
    # THÊM KHỐI LỆNH healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d learn2nihon"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/certs:/etc/nginx/certs/:ro
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge