
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:182705@db:5432/learn2nihon # Replace with your actual database URL
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes: # Giữ lại volume để code được đồng bộ
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=182705 
      - POSTGRES_DB=learn2nihon 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Thêm port mapping cho database  
    # THÊM KHỐI LỆNH healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d learn2nihon"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: