"""Add reading_item table

Revision ID: 9a9908110a07
Revises: a1c2d92cdc8b
Create Date: 2025-08-06 16:12:36.379297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9908110a07'
down_revision: Union[str, Sequence[str], None] = 'a1c2d92cdc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_items_id'), table_name='reading_items')
    op.drop_index(op.f('ix_reading_items_title'), table_name='reading_items')
    op.drop_table('reading_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('choices', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_items_pkey'))
    )
    op.create_index(op.f('ix_reading_items_title'), 'reading_items', ['title'], unique=False)
    op.create_index(op.f('ix_reading_items_id'), 'reading_items', ['id'], unique=False)
    # ### end Alembic commands ###
