"""nothing

Revision ID: ed518c46ba6c
Revises: 97021005d700
Create Date: 2025-07-10 17:09:38.827195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed518c46ba6c'
down_revision: Union[str, Sequence[str], None] = '97021005d700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'description')
    # ### end Alembic commands ###
